name: Build & Deploy Konfigurator

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build
        
      - name: Deploy dist via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: 22
          source: "dist/*"
          target: ${{ secrets.SFTP_PATH }}
          strip_components: 1
          overwrite: true
          timeout: 120s
